
sudo: required
dist: trusty
language: node_js
node_js:
  - "9.5"
  
before_script:
  - npm i npm@latest -g
  - npm install -g --silent @angular/cli

script:
  - ng lint
  - ng build --prod

after_success:

