
sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable

node_js:
  - "9.5"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g --silent @angular/cli
  - npm install

script:
  - ng lint
  - ng build --prod

after_success:

notifications:
  email:
    on_failure: always
on_success: change